### ISSUE TITLE
如何部署到服务器？

### ISSUE THREAD

**Issue by xdwxls** [tangdaohai/vue-ssr-demo#3]
这个服务端渲染 demo 如何部署到服务器上？ 将npm run build 生成的文件放置到服务器，报错403错

**Comment by tangdaohai** [comment]
可以贴一下详细信息吗？确认下403是 node 抛出的还是 Nginx 类的代理抛出的. @xdwxls

**Comment by xdwxls** [comment]
![image](https://user-images.githubusercontent.com/9478777/43057408-b1848dea-8e74-11e8-827c-899158cc88b5.png)
刚看了下？确实是nginx报的错，应该如何处理呢

**Comment by xdwxls** [comment]
@tangdaohai 
![image](https://user-images.githubusercontent.com/9478777/43057432-db6eebb4-8e74-11e8-8750-68bea0ff22c2.png)
确实是nginx 抛的错，我只是将 npm run build 生成的文件放在配置好的nginx对应目录下，那应该如何处理呢？

**Comment by xdwxls** [comment]
@tangdaohai 是nginx 抛出的，因为nginx 默认找不到index.html index.htm 页面，所以报错。因为执行npm run build 没有生成index.html
