### ISSUE TITLE
npm run build 的时候老报这个错，求大神指点

### ISSUE THREAD

**Issue by wpiami** [tangdaohai/vue-ssr-demo#4]
ERROR in ./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4a9894ad","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (C:\Users\Administrator\Desktop\vue-demo\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)
 @ ./src/App.vue 3:4-360
 @ ./src/main.js
 @ ./src/entry-server.js

**Comment by tangdaohai** [comment]
webpack 的配置有修改过吗？有的话请贴下代码

**Comment by vanbolee** [comment]
遇到同样的问题，按照步骤从vue-cli开始，一步步改ssr，最后build报错extract-text-webpack-plugin问题
vue-cli没修改直接run dev/build是可以的
直接clone此demo也能正常显示

**Comment by tangdaohai** [comment]
@vanbolee 第三方库版本不一致问题导致。这个demo库依赖的版本比较老了，现在基于`vue-cli3`搭建的项目直接复制demo配置会出问题的。
